import type { Product } from './types';
import { calcOverallScore } from './scoring';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    slug: 'the-golden-secrets-face-serum',
    name: 'Youth Beauty Face Oil',
    brand: 'The Golden Secrets',
    tagline: 'Luxury meets function — skin support rooted in Ayurvedic wisdom.',
    description:
      'A richly formulated face oil blending 24k gold, plant actives, and botanical oils. Designed to nourish and restore radiance while supporting the skin barrier.',
    category: ['face-oil'],
    skinTypes: ['dry', 'normal', 'mature'],
    skinConcerns: ['hydration', 'glow', 'firmness', 'dullness'],
    ingredientFocus: ['antioxidants', 'plant-stem-cells'],
    philosophy: ['clean-beauty', 'luxury', 'cultural-heritage'],
    routineLevel: 'moderate',
    price: 89,
    priceRange: 'premium',
    affiliateUrl: 'https://bit.ly/3xwBvkm',
    affiliatePartner: 'The Golden Secrets',
    image: '/images/products/tgs_youthbeautyfaceoil.webp',
    tier: 'A',
    overallScore: 8.4,
    isAgeSupport: true,
    scores: {
      results: 8.5,
      feelExperience: 9.0,
      ingredientsSafety: 8.0,
      skinCompatibility: 8.5,
      easeOfUse: 9.0,
      brandTrust: 8.0,
      priceValue: 7.5,
      aestheticPackaging: 9.5,
    },
    ageDecadeScores: {
      twenties: 7.5,
      thirties: 8.5,
      forties: 9.0,
      fifties: 8.5,
      sixtyPlus: 8.0,
    },
    pros: [
      'Deeply nourishing without heaviness',
      'Visible glow within 1–2 weeks',
      'Beautiful sensory experience',
      'Clean ingredient profile',
    ],
    cons: ['Premium price point', 'Not ideal for oily or acne-prone skin'],
    bestFor: 'Dry to normal skin seeking a luxurious daily radiance serum',
    notGreatFor: 'Oily or acne-prone skin types',
    keyIngredients: ['24k Gold', 'Rosehip Oil', 'Sea Buckthorn', 'Turmeric', 'Vitamin E'],
    publishedAt: '2024-09-01',
    updatedAt: '2025-01-15',
  },
  {
    id: '2',
    slug: 'osea-ocean-cleanser',
    name: 'Ocean Cleanser',
    brand: 'OSEA',
    tagline: 'Seaweed-powered cleansing that respects your barrier.',
    description:
      "A gentle, sulfate-free gel cleanser formulated with OSEA's signature seaweed blend. Removes impurities without stripping skin of its natural moisture.",
    category: ['cleanser'],
    skinTypes: ['normal', 'combination', 'sensitive', 'dry'],
    skinConcerns: ['hydration', 'barrier-repair', 'redness'],
    ingredientFocus: ['sea-actives', 'antioxidants'],
    philosophy: ['clean-beauty', 'vegan', 'cruelty-free', 'reef-safe', 'sustainable'],
    routineLevel: 'simple',
    price: 48,
    priceRange: 'mid',
    affiliateUrl:
      'https://oseamalibu.com/?rfsn=7790532.88631ca&utm_source=refersion&utm_medium=affiliate&utm_campaign=7790532.88631ca',
    affiliatePartner: 'OSEA',
    image: '/images/products/oseaOC-5_fl_oz_pump.webp',
    tier: 'A',
    overallScore: 8.6,
    isAgeSupport: true,
    scores: {
      results: 8.5,
      feelExperience: 9.0,
      ingredientsSafety: 9.5,
      skinCompatibility: 9.0,
      easeOfUse: 9.5,
      brandTrust: 9.0,
      priceValue: 8.0,
      aestheticPackaging: 8.0,
    },
    ageDecadeScores: {
      twenties: 9.0,
      thirties: 9.0,
      forties: 8.5,
      fifties: 8.5,
      sixtyPlus: 8.0,
    },
    pros: [
      'Works for nearly all skin types',
      'Reef-safe and sustainably sourced',
      'Leaves skin soft, not tight',
      'Strong clean beauty ethos',
    ],
    cons: ['Some find the seaweed scent polarizing', 'No heavy-duty makeup removal'],
    bestFor: 'Everyday cleansing for sensitive and normal skin types seeking clean formulas',
    keyIngredients: ['Atlantic Kelp', 'Bladderwrack Seaweed', 'Aloe Vera', 'Glycerin'],
    publishedAt: '2024-08-15',
    updatedAt: '2025-02-01',
  },
  {
    id: '3',
    slug: 'osea-undaria-algae-body-serum',
    name: 'Undaria Algae Body Oil',
    brand: 'OSEA',
    tagline: 'Award-winning body oil for visibly smoother, nourished skin.',
    description:
      "OSEA's hero product — a lightweight, fast-absorbing body oil packed with nutrient-rich Undaria algae. Clinically shown to improve skin texture and hydration.",
    category: ['face-oil'],
    skinTypes: ['dry', 'normal', 'combination', 'mature'],
    skinConcerns: ['texture', 'hydration', 'firmness', 'glow'],
    ingredientFocus: ['sea-actives', 'antioxidants', 'hyaluronic-acid'],
    philosophy: ['clean-beauty', 'vegan', 'cruelty-free', 'reef-safe', 'sustainable'],
    routineLevel: 'simple',
    price: 68,
    priceRange: 'premium',
    affiliateUrl:
      'https://oseamalibu.com/?rfsn=7790532.88631ca&utm_source=refersion&utm_medium=affiliate&utm_campaign=7790532.88631ca',
    affiliatePartner: 'OSEA',
    image: '/images/products/OSEA_UndariaAlgaeBodyOil_UAO-295-DTC-1_badgeless.webp',
    tier: 'S',
    overallScore: 9.1,
    isAgeSupport: true,
    scores: {
      results: 9.5,
      feelExperience: 9.5,
      ingredientsSafety: 9.5,
      skinCompatibility: 9.0,
      easeOfUse: 9.5,
      brandTrust: 9.0,
      priceValue: 8.5,
      aestheticPackaging: 8.5,
    },
    ageDecadeScores: {
      twenties: 8.5,
      thirties: 9.0,
      forties: 9.5,
      fifties: 9.5,
      sixtyPlus: 9.0,
    },
    pros: [
      'Clinically proven texture improvement',
      'Fast-absorbing, never greasy',
      'One of the cleanest body oils on the market',
      'Award-winning formula',
    ],
    cons: ['Price point higher than most body lotions', 'Scented — may not suit fragrance-sensitive skin'],
    bestFor: 'Anyone wanting clinically-backed, clean body skin support in one step',
    keyIngredients: ['Undaria Pinnatifida Algae', 'Hyaluronic Acid', 'Vitamin C', 'Niacinamide'],
    publishedAt: '2024-07-01',
    updatedAt: '2025-03-01',
  },
  {
    id: '4',
    slug: 'true-botanicals-vitamin-c-booster',
    name: 'Vitamin C Booster',
    brand: 'True Botanicals',
    tagline: 'Stabilized, potent Vitamin C that actually delivers.',
    description:
      'A concentrated Vitamin C powder that activates on contact with your serum or moisturizer. One of the most stable and effective Vitamin C formulations in clean beauty.',
    category: ['serum'],
    skinTypes: ['normal', 'combination', 'dry', 'mature'],
    skinConcerns: ['dark-spots', 'dullness', 'glow', 'firmness', 'fine-lines'],
    ingredientFocus: ['vitamin-c', 'antioxidants'],
    philosophy: ['clean-beauty', 'cruelty-free', 'sustainable', 'clinical'],
    routineLevel: 'moderate',
    price: 110,
    priceRange: 'luxury',
    affiliateUrl: 'https://true-botanicals.sjv.io/E09GAX',
    affiliatePartner: 'True Botanicals',
    image: '/images/products/tbVitaminCBooster.SILO.webp',
    tier: 'S',
    overallScore: 9.2,
    isAgeSupport: true,
    scores: {
      results: 9.5,
      feelExperience: 8.0,
      ingredientsSafety: 9.5,
      skinCompatibility: 9.0,
      easeOfUse: 7.5,
      brandTrust: 9.5,
      priceValue: 8.0,
      aestheticPackaging: 9.0,
    },
    ageDecadeScores: {
      twenties: 8.0,
      thirties: 9.0,
      forties: 9.5,
      fifties: 9.5,
      sixtyPlus: 9.0,
    },
    pros: [
      'Exceptional stability vs. liquid Vitamin C',
      'Highly bioavailable form (THD Ascorbate)',
      'Certified MADE SAFE',
      'Visible brightening within 4 weeks',
    ],
    cons: [
      'Learning curve with the powder format',
      'Luxury price point',
      'Needs a "carrier" product',
    ],
    bestFor: 'Committed routines seeking next-level brightening and skin tone support',
    notGreatFor: 'Beginners or those wanting a simple, one-step product',
    keyIngredients: ['THD Ascorbate (Vitamin C)', 'Ferulic Acid', 'Vitamin E'],
    publishedAt: '2024-06-15',
    updatedAt: '2025-01-20',
  },
  {
    id: '5',
    slug: 'juara-turmeric-antioxidant-radiance-mask',
    name: 'Radiance Vitality Oil',
    brand: 'Juara Skincare',
    tagline: 'Jamu-inspired face oil that brings warmth, glow, and deep nourishment.',
    description:
      'A nourishing face oil rooted in centuries-old Indonesian Jamu tradition. Candlenut oil, turmeric, and clove deliver antioxidant-rich skin support while promoting radiance and suppleness — skin care as a ritual.',
    category: ['face-oil'],
    skinTypes: ['normal', 'dry', 'combination', 'mature'],
    skinConcerns: ['glow', 'dullness', 'dark-spots', 'hydration', 'firmness'],
    ingredientFocus: ['antioxidants', 'plant-stem-cells'],
    philosophy: ['clean-beauty', 'cruelty-free', 'vegan', 'cultural-heritage'],
    routineLevel: 'moderate',
    price: 52,
    priceRange: 'mid',
    affiliateUrl: 'https://juara-skincare.sjv.io/enqBXZ',
    affiliatePartner: 'Juara Skincare',
    image: '/images/products/juara_vitalityoil.webp',
    tier: 'A',
    overallScore: 8.3,
    isAgeSupport: true,
    scores: {
      results: 8.5,
      feelExperience: 9.0,
      ingredientsSafety: 8.5,
      skinCompatibility: 8.0,
      easeOfUse: 8.5,
      brandTrust: 8.5,
      priceValue: 8.5,
      aestheticPackaging: 8.5,
    },
    ageDecadeScores: {
      twenties: 7.5,
      thirties: 8.5,
      forties: 9.0,
      fifties: 9.0,
      sixtyPlus: 8.5,
    },
    pros: [
      'Immediate radiance and warmth',
      'Beautiful ritual sensory experience',
      'Rooted in real cultural tradition',
      'Nourishing without heaviness',
    ],
    cons: ['Scented — not suitable for fragrance-sensitive skin', 'Heavier feel may not suit oily skin'],
    bestFor: 'Dry to normal skin seeking a nourishing, antioxidant-rich face oil with a ritual feel',
    notGreatFor: 'Oily or fragrance-sensitive skin',
    keyIngredients: ['Candlenut Oil', 'Turmeric Root', 'Clove', 'Tamanu Oil', 'Rosehip Oil'],
    publishedAt: '2024-10-01',
    updatedAt: '2026-04-17',
  },
  {
    id: '6',
    slug: 'shani-darden-texture-reform',
    name: 'Retinol Reform with 1% Encapsulated Retinol',
    brand: 'Shani Darden',
    tagline: 'Celebrity esthetician-formulated retinol that earns its reputation.',
    description:
      "Shani Darden's breakthrough formula with 1% encapsulated retinol and lactic acid for visible texture refinement. One of the most effective non-irritating retinol serums available.",
    category: ['serum', 'exfoliant'],
    skinTypes: ['normal', 'combination', 'oily', 'mature'],
    skinConcerns: ['texture', 'fine-lines', 'pores', 'dark-spots', 'anti-aging'],
    ingredientFocus: ['retinol', 'aha-bha'],
    philosophy: ['clinical', 'cruelty-free'],
    routineLevel: 'advanced',
    price: 88,
    priceRange: 'premium',
    affiliateUrl: 'https://shanidarden.sjv.io/5kAmzn',
    affiliatePartner: 'Shani Darden',
    image: '/images/products/sd_retinolreform.webp',
    tier: 'S',
    overallScore: 9.0,
    isAgeSupport: false,
    scores: {
      results: 9.5,
      feelExperience: 8.5,
      ingredientsSafety: 8.5,
      skinCompatibility: 8.5,
      easeOfUse: 8.0,
      brandTrust: 9.5,
      priceValue: 8.5,
      aestheticPackaging: 9.0,
    },
    ageDecadeScores: {
      twenties: 8.5,
      thirties: 9.5,
      forties: 9.0,
      fifties: 8.5,
      sixtyPlus: 7.5,
    },
    pros: [
      'Clinically effective texture resurfacing',
      'Retinol well-tolerated by most skin types',
      'Visible results in 4–6 weeks',
      'Trusted by professional estheticians',
    ],
    cons: ['Requires SPF during the day', 'Not for sensitive/reactive skin', 'No at night only use'],
    bestFor: 'Those wanting real skin texture improvement with clinical efficacy',
    notGreatFor: 'Sensitive, rosacea-prone, or retinol-naive skin without proper introduction',
    keyIngredients: ['Encapsulated Retinol', 'Lactic Acid', 'Niacinamide', 'Glycerin'],
    publishedAt: '2024-05-01',
    updatedAt: '2025-01-10',
  },
  {
    id: '7',
    slug: 'osea-hyaluronic-sea-serum',
    name: 'Hyaluronic Sea Serum',
    brand: 'OSEA',
    tagline: 'Plumping, weightless hydration from the deep sea.',
    description:
      "A featherlight serum delivering three weights of hyaluronic acid alongside OSEA's signature seaweed complex for multi-depth hydration. Works for every skin type.",
    category: ['serum'],
    skinTypes: ['dry', 'oily', 'combination', 'sensitive', 'normal', 'mature'],
    skinConcerns: ['hydration', 'barrier-repair', 'fine-lines'],
    ingredientFocus: ['hyaluronic-acid', 'sea-actives'],
    philosophy: ['clean-beauty', 'vegan', 'cruelty-free', 'reef-safe'],
    routineLevel: 'simple',
    price: 72,
    priceRange: 'premium',
    affiliateUrl:
      'https://oseamalibu.com/?rfsn=7790532.88631ca&utm_source=refersion&utm_medium=affiliate&utm_campaign=7790532.88631ca',
    affiliatePartner: 'OSEA',
    image: '/images/products/osea_hylauronicseaserum.avif',
    tier: 'A',
    overallScore: 8.8,
    isAgeSupport: true,
    scores: {
      results: 9.0,
      feelExperience: 9.5,
      ingredientsSafety: 9.5,
      skinCompatibility: 9.5,
      easeOfUse: 9.5,
      brandTrust: 9.0,
      priceValue: 7.5,
      aestheticPackaging: 8.5,
    },
    ageDecadeScores: {
      twenties: 9.0,
      thirties: 9.0,
      forties: 9.0,
      fifties: 8.5,
      sixtyPlus: 8.5,
    },
    pros: [
      'Works beautifully across all skin types',
      'Multi-weight HA for surface and deep hydration',
      'Lightweight — layers under everything',
      'Exceptional clean beauty credentials',
    ],
    cons: ['Premium price for a HA serum', 'Must be applied to damp skin for best results'],
    bestFor: 'Anyone seeking a reliable, clean hydration serum as a routine staple',
    keyIngredients: ['3-Weight Hyaluronic Acid', 'Atlantic Kelp', 'Spirulina', 'Sea Buckthorn'],
    publishedAt: '2024-08-01',
    updatedAt: '2025-02-28',
  },
  {
    id: '8',
    slug: 'true-botanicals-pure-radiance-oil',
    name: 'Pure Radiance Oil',
    brand: 'True Botanicals',
    tagline: 'A single-ingredient nourishing face oil that works.',
    description:
      "True Botanicals' cult-status face oil made with Camellia seed oil. Clinically tested, fragrance-free, and one of the most universally compatible face oils on the market.",
    category: ['face-oil'],
    skinTypes: ['dry', 'normal', 'mature', 'sensitive'],
    skinConcerns: ['hydration', 'barrier-repair', 'glow', 'firmness'],
    ingredientFocus: ['antioxidants'],
    philosophy: ['clean-beauty', 'cruelty-free', 'fragrance-free', 'clinical', 'minimalist'],
    routineLevel: 'simple',
    price: 110,
    priceRange: 'luxury',
    affiliateUrl: 'https://true-botanicals.sjv.io/E09GAX',
    affiliatePartner: 'True Botanicals',
    image: '/images/products/tb_RenewPureRadianceOil30mL.webp',
    tier: 'A',
    overallScore: 8.7,
    isAgeSupport: true,
    scores: {
      results: 9.0,
      feelExperience: 9.0,
      ingredientsSafety: 9.5,
      skinCompatibility: 9.0,
      easeOfUse: 9.0,
      brandTrust: 9.5,
      priceValue: 7.0,
      aestheticPackaging: 8.5,
    },
    ageDecadeScores: {
      twenties: 7.5,
      thirties: 8.5,
      forties: 9.0,
      fifties: 9.0,
      sixtyPlus: 9.0,
    },
    pros: [
      'Fragrance-free and MADE SAFE certified',
      'Exceptional for dry and mature skin types',
      'Clinically tested efficacy',
      'One of the cleanest face oils available',
    ],
    cons: ['Very high price for a single-ingredient oil', 'Not ideal for oily/acne-prone skin'],
    bestFor: 'Dry, mature, or sensitive skin seeking a clean, fragrance-free nourishing face oil',
    keyIngredients: ['Camellia japonica Seed Oil', 'Squalane'],
    publishedAt: '2024-04-15',
    updatedAt: '2025-01-05',
  },
  {
    id: '9',
    slug: 'medicube-zero-pore-pad-2',
    name: 'Zero Pore Pad 2.0',
    brand: 'Medicube',
    tagline: 'K-beauty AHA/BHA pads that visibly minimize pores and refine texture — at a drugstore price.',
    description:
      'Clinically tested toner pads combining lactic acid (AHA) for surface exfoliation and salicylic acid (BHA) for deep pore-clearing. Designed for oily, combination, and normal skin types seeking smoother texture and reduced pore appearance. Use a maximum of 3 times per week; always follow with SPF. Currently on sale from $31.',
    category: ['toner', 'exfoliant'],
    skinTypes: ['oily', 'combination', 'normal'],
    skinConcerns: ['pores', 'texture', 'dullness', 'glow'],
    ingredientFocus: ['aha-bha'],
    philosophy: ['fragrance-free', 'clinical', 'cultural-heritage'],
    routineLevel: 'moderate',
    price: 18.90,
    priceRange: 'budget',
    affiliateUrl: 'https://www.amazon.com/dp/B0CW1KV8B6?tag=skincareprice-20',
    affiliatePartner: 'Amazon',
    image: '/images/products/medicube-zero-pore-pad.jpg',
    tier: 'A',
    overallScore: 8.7,
    isAgeSupport: false,
    scores: {
      results: 8.8,
      feelExperience: 8.5,
      ingredientsSafety: 8.7,
      skinCompatibility: 7.8,
      easeOfUse: 9.5,
      brandTrust: 9.0,
      priceValue: 9.4,
      aestheticPackaging: 8.2,
    },
    ageDecadeScores: {
      twenties: 9.0,
      thirties: 9.0,
      forties: 8.5,
      fifties: 7.0,
      sixtyPlus: 6.0,
    },
    pros: [
      'Exceptional value — effective AHA/BHA at a budget price',
      'Noticeably minimizes pores with consistent use',
      'Incredibly easy to use — no cotton pad needed',
      'Dermatologist-tested and fragrance-free',
      'K-beauty clinically backed formula',
    ],
    cons: [
      'Not suitable for very dry or sensitive skin',
      'Requires SPF every morning when in use',
      'Max 3x per week — overuse causes irritation',
      'Not ideal for skin in its 50s+ without gradual introduction',
    ],
    bestFor: 'Oily, combination, or normal skin with enlarged pores, uneven texture, or dullness',
    notGreatFor: 'Very dry, sensitive, or reactive skin — introduce slowly if in doubt',
    keyIngredients: ['Lactic Acid (AHA)', 'Salicylic Acid (BHA)', 'Niacinamide', 'Glycerin'],
    publishedAt: '2025-04-16',
    updatedAt: '2025-04-16',
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByTier(tier: string): Product[] {
  return PRODUCTS.filter((p) => p.tier === tier);
}

export function getAgeSupportProducts(): Product[] {
  return PRODUCTS.filter((p) => p.isAgeSupport);
}
