import type { Product } from './types';
import { calcOverallScore } from './scoring';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    slug: 'the-golden-secrets-face-serum',
    name: 'Youth Beauty Face Oil',
    brand: 'The Golden Secrets',
    tagline: 'Luxury meets function — skin support rooted in Ayurvedic wisdom.',
    description:
      'A richly formulated face oil blending 24k gold, plant actives, and botanical oils. Designed to nourish and restore radiance while supporting the skin barrier.',
    category: ['face-oil'],
    skinTypes: ['dry', 'normal', 'mature'],
    skinConcerns: ['hydration', 'glow', 'firmness', 'dullness'],
    ingredientFocus: ['antioxidants', 'plant-stem-cells'],
    philosophy: ['clean-beauty', 'luxury', 'cultural-heritage'],
    routineLevel: 'moderate',
    price: 89,
    priceRange: 'premium',
    affiliateUrl: 'https://bit.ly/3xwBvkm',
    affiliatePartner: 'The Golden Secrets',
    image: '/images/products/tgs_youthbeautyfaceoil.webp',
    tier: 'A',
    overallScore: 8.4,
    isAgeSupport: true,
    scores: {
      results: 8.5,
      feelExperience: 9.0,
      ingredientsSafety: 8.0,
      skinCompatibility: 8.5,
      easeOfUse: 9.0,
      brandTrust: 8.0,
      priceValue: 7.5,
      aestheticPackaging: 9.5,
    },
    ageDecadeScores: {
      twenties: 7.5,
      thirties: 8.5,
      forties: 9.0,
      fifties: 8.5,
      sixtyPlus: 8.0,
    },
    pros: [
      'Deeply nourishing without heaviness',
      'Visible glow within 1–2 weeks',
      'Beautiful sensory experience',
      'Clean ingredient profile',
    ],
    cons: ['Premium price point', 'Not ideal for oily or acne-prone skin'],
    bestFor: 'Dry to normal skin seeking a luxurious daily radiance serum',
    notGreatFor: 'Oily or acne-prone skin types',
    keyIngredients: ['24k Gold', 'Rosehip Oil', 'Sea Buckthorn', 'Turmeric', 'Vitamin E'],
    publishedAt: '2024-09-01',
    updatedAt: '2025-01-15',
  },
  {
    id: '2',
    slug: 'osea-ocean-cleanser',
    name: 'Ocean Cleanser',
    brand: 'OSEA',
    tagline: 'Seaweed-powered cleansing that respects your barrier.',
    description:
      "A gentle, sulfate-free gel cleanser formulated with OSEA's signature seaweed blend. Removes impurities without stripping skin of its natural moisture.",
    category: ['cleanser'],
    skinTypes: ['normal', 'combination', 'sensitive', 'dry'],
    skinConcerns: ['hydration', 'barrier-repair', 'redness'],
    ingredientFocus: ['sea-actives', 'antioxidants'],
    philosophy: ['clean-beauty', 'vegan', 'cruelty-free', 'reef-safe', 'sustainable'],
    routineLevel: 'simple',
    price: 48,
    priceRange: 'mid',
    affiliateUrl:
      'https://oseamalibu.com/?rfsn=7790532.88631ca&utm_source=refersion&utm_medium=affiliate&utm_campaign=7790532.88631ca',
    affiliatePartner: 'OSEA',
    image: '/images/products/oseaOC-5_fl_oz_pump.webp',
    tier: 'A',
    overallScore: 8.6,
    isAgeSupport: true,
    scores: {
      results: 8.5,
      feelExperience: 9.0,
      ingredientsSafety: 9.5,
      skinCompatibility: 9.0,
      easeOfUse: 9.5,
      brandTrust: 9.0,
      priceValue: 8.0,
      aestheticPackaging: 8.0,
    },
    ageDecadeScores: {
      twenties: 9.0,
      thirties: 9.0,
      forties: 8.5,
      fifties: 8.5,
      sixtyPlus: 8.0,
    },
    pros: [
      'Works for nearly all skin types',
      'Reef-safe and sustainably sourced',
      'Leaves skin soft, not tight',
      'Strong clean beauty ethos',
    ],
    cons: ['Some find the seaweed scent polarizing', 'No heavy-duty makeup removal'],
    bestFor: 'Everyday cleansing for sensitive and normal skin types seeking clean formulas',
    keyIngredients: ['Atlantic Kelp', 'Bladderwrack Seaweed', 'Aloe Vera', 'Glycerin'],
    publishedAt: '2024-08-15',
    updatedAt: '2025-02-01',
  },
  {
    id: '3',
    slug: 'osea-undaria-algae-body-serum',
    name: 'Undaria Algae Body Oil',
    brand: 'OSEA',
    tagline: 'Award-winning body oil for visibly smoother, nourished skin.',
    description:
      "OSEA's hero product — a lightweight, fast-absorbing body oil packed with nutrient-rich Undaria algae. Clinically shown to improve skin texture and hydration.",
    category: ['face-oil'],
    skinTypes: ['dry', 'normal', 'combination', 'mature'],
    skinConcerns: ['texture', 'hydration', 'firmness', 'glow'],
    ingredientFocus: ['sea-actives', 'antioxidants', 'hyaluronic-acid'],
    philosophy: ['clean-beauty', 'vegan', 'cruelty-free', 'reef-safe', 'sustainable'],
    routineLevel: 'simple',
    price: 68,
    priceRange: 'premium',
    affiliateUrl:
      'https://oseamalibu.com/?rfsn=7790532.88631ca&utm_source=refersion&utm_medium=affiliate&utm_campaign=7790532.88631ca',
    affiliatePartner: 'OSEA',
    image: '/images/products/OSEA_UndariaAlgaeBodyOil_UAO-295-DTC-1_badgeless.webp',
    tier: 'S',
    overallScore: 9.1,
    isAgeSupport: true,
    scores: {
      results: 9.5,
      feelExperience: 9.5,
      ingredientsSafety: 9.5,
      skinCompatibility: 9.0,
      easeOfUse: 9.5,
      brandTrust: 9.0,
      priceValue: 8.5,
      aestheticPackaging: 8.5,
    },
    ageDecadeScores: {
      twenties: 8.5,
      thirties: 9.0,
      forties: 9.5,
      fifties: 9.5,
      sixtyPlus: 9.0,
    },
    pros: [
      'Clinically proven texture improvement',
      'Fast-absorbing, never greasy',
      'One of the cleanest body oils on the market',
      'Award-winning formula',
    ],
    cons: ['Price point higher than most body lotions', 'Scented — may not suit fragrance-sensitive skin'],
    bestFor: 'Anyone wanting clinically-backed, clean body skin support in one step',
    keyIngredients: ['Undaria Pinnatifida Algae', 'Hyaluronic Acid', 'Vitamin C', 'Niacinamide'],
    publishedAt: '2024-07-01',
    updatedAt: '2025-03-01',
  },
  {
    id: '4',
    slug: 'true-botanicals-vitamin-c-booster',
    name: 'Vitamin C Booster',
    brand: 'True Botanicals',
    tagline: 'Stabilized, potent Vitamin C that actually delivers.',
    description:
      'A concentrated Vitamin C powder that activates on contact with your serum or moisturizer. One of the most stable and effective Vitamin C formulations in clean beauty.',
    category: ['serum'],
    skinTypes: ['normal', 'combination', 'dry', 'mature'],
    skinConcerns: ['dark-spots', 'dullness', 'glow', 'firmness', 'fine-lines'],
    ingredientFocus: ['vitamin-c', 'antioxidants'],
    philosophy: ['clean-beauty', 'cruelty-free', 'sustainable', 'clinical'],
    routineLevel: 'moderate',
    price: 110,
    priceRange: 'luxury',
    affiliateUrl: 'https://true-botanicals.sjv.io/E09GAX',
    affiliatePartner: 'True Botanicals',
    image: '/images/products/tbVitaminCBooster.SILO.webp',
    tier: 'S',
    overallScore: 9.2,
    isAgeSupport: true,
    scores: {
      results: 9.5,
      feelExperience: 8.0,
      ingredientsSafety: 9.5,
      skinCompatibility: 9.0,
      easeOfUse: 7.5,
      brandTrust: 9.5,
      priceValue: 8.0,
      aestheticPackaging: 9.0,
    },
    ageDecadeScores: {
      twenties: 8.0,
      thirties: 9.0,
      forties: 9.5,
      fifties: 9.5,
      sixtyPlus: 9.0,
    },
    pros: [
      'Exceptional stability vs. liquid Vitamin C',
      'Highly bioavailable form (THD Ascorbate)',
      'Certified MADE SAFE',
      'Visible brightening within 4 weeks',
    ],
    cons: [
      'Learning curve with the powder format',
      'Luxury price point',
      'Needs a "carrier" product',
    ],
    bestFor: 'Committed routines seeking next-level brightening and skin tone support',
    notGreatFor: 'Beginners or those wanting a simple, one-step product',
    keyIngredients: ['THD Ascorbate (Vitamin C)', 'Ferulic Acid', 'Vitamin E'],
    publishedAt: '2024-06-15',
    updatedAt: '2025-01-20',
  },
  {
    id: '5',
    slug: 'juara-turmeric-antioxidant-radiance-mask',
    name: 'Radiance Vitality Oil',
    brand: 'Juara Skincare',
    tagline: 'Jamu-inspired face oil that brings warmth, glow, and deep nourishment.',
    description:
      'A nourishing face oil rooted in centuries-old Indonesian Jamu tradition. Candlenut oil, turmeric, and clove deliver antioxidant-rich skin support while promoting radiance and suppleness — skin care as a ritual.',
    category: ['face-oil'],
    skinTypes: ['normal', 'dry', 'combination', 'mature'],
    skinConcerns: ['glow', 'dullness', 'dark-spots', 'hydration', 'firmness'],
    ingredientFocus: ['antioxidants', 'plant-stem-cells'],
    philosophy: ['clean-beauty', 'cruelty-free', 'vegan', 'cultural-heritage'],
    routineLevel: 'moderate',
    price: 52,
    priceRange: 'mid',
    affiliateUrl: 'https://juara-skincare.sjv.io/enqBXZ',
    affiliatePartner: 'Juara Skincare',
    image: '/images/products/juara_vitalityoil.webp',
    tier: 'A',
    overallScore: 8.3,
    isAgeSupport: true,
    scores: {
      results: 8.5,
      feelExperience: 9.0,
      ingredientsSafety: 8.5,
      skinCompatibility: 8.0,
      easeOfUse: 8.5,
      brandTrust: 8.5,
      priceValue: 8.5,
      aestheticPackaging: 8.5,
    },
    ageDecadeScores: {
      twenties: 7.5,
      thirties: 8.5,
      forties: 9.0,
      fifties: 9.0,
      sixtyPlus: 8.5,
    },
    pros: [
      'Immediate radiance and warmth',
      'Beautiful ritual sensory experience',
      'Rooted in real cultural tradition',
      'Nourishing without heaviness',
    ],
    cons: ['Scented — not suitable for fragrance-sensitive skin', 'Heavier feel may not suit oily skin'],
    bestFor: 'Dry to normal skin seeking a nourishing, antioxidant-rich face oil with a ritual feel',
    notGreatFor: 'Oily or fragrance-sensitive skin',
    keyIngredients: ['Candlenut Oil', 'Turmeric Root', 'Clove', 'Tamanu Oil', 'Rosehip Oil'],
    publishedAt: '2024-10-01',
    updatedAt: '2026-04-17',
  },
  {
    id: '6',
    slug: 'shani-darden-texture-reform',
    name: 'Retinol Reform with 1% Encapsulated Retinol',
    brand: 'Shani Darden',
    tagline: 'Celebrity esthetician-formulated retinol that earns its reputation.',
    description:
      "Shani Darden's breakthrough formula with 1% encapsulated retinol and lactic acid for visible texture refinement. One of the most effective non-irritating retinol serums available.",
    category: ['serum', 'exfoliant'],
    skinTypes: ['normal', 'combination', 'oily', 'mature'],
    skinConcerns: ['texture', 'fine-lines', 'pores', 'dark-spots', 'anti-aging'],
    ingredientFocus: ['retinol', 'aha-bha'],
    philosophy: ['clinical', 'cruelty-free'],
    routineLevel: 'advanced',
    price: 88,
    priceRange: 'premium',
    affiliateUrl: 'https://shanidarden.sjv.io/5kAmzn',
    affiliatePartner: 'Shani Darden',
    image: '/images/products/sd_retinolreform.webp',
    tier: 'S',
    overallScore: 9.0,
    isAgeSupport: false,
    scores: {
      results: 9.5,
      feelExperience: 8.5,
      ingredientsSafety: 8.5,
      skinCompatibility: 8.5,
      easeOfUse: 8.0,
      brandTrust: 9.5,
      priceValue: 8.5,
      aestheticPackaging: 9.0,
    },
    ageDecadeScores: {
      twenties: 8.5,
      thirties: 9.5,
      forties: 9.0,
      fifties: 8.5,
      sixtyPlus: 7.5,
    },
    pros: [
      'Clinically effective texture resurfacing',
      'Retinol well-tolerated by most skin types',
      'Visible results in 4–6 weeks',
      'Trusted by professional estheticians',
    ],
    cons: ['Requires SPF during the day', 'Not for sensitive/reactive skin', 'No at night only use'],
    bestFor: 'Those wanting real skin texture improvement with clinical efficacy',
    notGreatFor: 'Sensitive, rosacea-prone, or retinol-naive skin without proper introduction',
    keyIngredients: ['Encapsulated Retinol', 'Lactic Acid', 'Niacinamide', 'Glycerin'],
    publishedAt: '2024-05-01',
    updatedAt: '2025-01-10',
  },
  {
    id: '7',
    slug: 'osea-hyaluronic-sea-serum',
    name: 'Hyaluronic Sea Serum',
    brand: 'OSEA',
    tagline: 'Plumping, weightless hydration from the deep sea.',
    description:
      "A featherlight serum delivering three weights of hyaluronic acid alongside OSEA's signature seaweed complex for multi-depth hydration. Works for every skin type.",
    category: ['serum'],
    skinTypes: ['dry', 'oily', 'combination', 'sensitive', 'normal', 'mature'],
    skinConcerns: ['hydration', 'barrier-repair', 'fine-lines'],
    ingredientFocus: ['hyaluronic-acid', 'sea-actives'],
    philosophy: ['clean-beauty', 'vegan', 'cruelty-free', 'reef-safe'],
    routineLevel: 'simple',
    price: 72,
    priceRange: 'premium',
    affiliateUrl:
      'https://oseamalibu.com/?rfsn=7790532.88631ca&utm_source=refersion&utm_medium=affiliate&utm_campaign=7790532.88631ca',
    affiliatePartner: 'OSEA',
    image: '/images/products/osea_hylauronicseaserum.avif',
    tier: 'A',
    overallScore: 8.8,
    isAgeSupport: true,
    scores: {
      results: 9.0,
      feelExperience: 9.5,
      ingredientsSafety: 9.5,
      skinCompatibility: 9.5,
      easeOfUse: 9.5,
      brandTrust: 9.0,
      priceValue: 7.5,
      aestheticPackaging: 8.5,
    },
    ageDecadeScores: {
      twenties: 9.0,
      thirties: 9.0,
      forties: 9.0,
      fifties: 8.5,
      sixtyPlus: 8.5,
    },
    pros: [
      'Works beautifully across all skin types',
      'Multi-weight HA for surface and deep hydration',
      'Lightweight — layers under everything',
      'Exceptional clean beauty credentials',
    ],
    cons: ['Premium price for a HA serum', 'Must be applied to damp skin for best results'],
    bestFor: 'Anyone seeking a reliable, clean hydration serum as a routine staple',
    keyIngredients: ['3-Weight Hyaluronic Acid', 'Atlantic Kelp', 'Spirulina', 'Sea Buckthorn'],
    publishedAt: '2024-08-01',
    updatedAt: '2025-02-28',
  },
  {
    id: '8',
    slug: 'true-botanicals-pure-radiance-oil',
    name: 'Pure Radiance Oil',
    brand: 'True Botanicals',
    tagline: 'A single-ingredient nourishing face oil that works.',
    description:
      "True Botanicals' cult-status face oil made with Camellia seed oil. Clinically tested, fragrance-free, and one of the most universally compatible face oils on the market.",
    category: ['face-oil'],
    skinTypes: ['dry', 'normal', 'mature', 'sensitive'],
    skinConcerns: ['hydration', 'barrier-repair', 'glow', 'firmness'],
    ingredientFocus: ['antioxidants'],
    philosophy: ['clean-beauty', 'cruelty-free', 'fragrance-free', 'clinical', 'minimalist'],
    routineLevel: 'simple',
    price: 110,
    priceRange: 'luxury',
    affiliateUrl: 'https://true-botanicals.sjv.io/E09GAX',
    affiliatePartner: 'True Botanicals',
    image: '/images/products/tb_RenewPureRadianceOil30mL.webp',
    tier: 'A',
    overallScore: 8.7,
    isAgeSupport: true,
    scores: {
      results: 9.0,
      feelExperience: 9.0,
      ingredientsSafety: 9.5,
      skinCompatibility: 9.0,
      easeOfUse: 9.0,
      brandTrust: 9.5,
      priceValue: 7.0,
      aestheticPackaging: 8.5,
    },
    ageDecadeScores: {
      twenties: 7.5,
      thirties: 8.5,
      forties: 9.0,
      fifties: 9.0,
      sixtyPlus: 9.0,
    },
    pros: [
      'Fragrance-free and MADE SAFE certified',
      'Exceptional for dry and mature skin types',
      'Clinically tested efficacy',
      'One of the cleanest face oils available',
    ],
    cons: ['Very high price for a single-ingredient oil', 'Not ideal for oily/acne-prone skin'],
    bestFor: 'Dry, mature, or sensitive skin seeking a clean, fragrance-free nourishing face oil',
    keyIngredients: ['Camellia japonica Seed Oil', 'Squalane'],
    publishedAt: '2024-04-15',
    updatedAt: '2025-01-05',
  },
  {
    id: '10',
    slug: 'cosrx-snail-96-mucin-essence-starter-set',
    name: 'Snail 96 Mucin Power Essence — Glass Skin Starter Set',
    brand: 'COSRX',
    tagline: "K-beauty's most beloved essence: 96% snail mucin for deep hydration and barrier repair.",
    description:
      'An Amazon Exclusive Glass Skin Starter Set featuring two full-size Snail 96% Mucin Power Essences plus a Retinol 0.1% Cream mini sample. The essence — COSRX\'s cult hero — delivers 96% snail secretion filtrate for proven hydration, barrier repair, and skin calming. Lightweight gel texture absorbs quickly. Use morning and evening on clean skin before moisturizer.',
    category: ['serum'],
    skinTypes: ['dry', 'oily', 'combination', 'sensitive', 'normal', 'mature'],
    skinConcerns: ['hydration', 'barrier-repair', 'redness', 'fine-lines', 'dullness'],
    ingredientFocus: ['antioxidants', 'retinol'],
    philosophy: ['cruelty-free', 'clinical', 'cultural-heritage'],
    routineLevel: 'simple',
    price: 35,
    priceRange: 'budget',
    affiliateUrl: 'https://www.amazon.com/dp/B0C1Y8652X?tag=skincareprice-20',
    affiliatePartner: 'Amazon',
    image: '/images/products/COSRX_SNAILMUCUS.jpg',
    tier: 'A',
    overallScore: 8.6,
    isAgeSupport: true,
    scores: {
      results: 8.5,
      feelExperience: 7.5,
      ingredientsSafety: 8.8,
      skinCompatibility: 9.0,
      easeOfUse: 9.0,
      brandTrust: 9.0,
      priceValue: 9.5,
      aestheticPackaging: 7.5,
    },
    ageDecadeScores: {
      twenties: 9.0,
      thirties: 9.0,
      forties: 8.5,
      fifties: 8.0,
      sixtyPlus: 7.5,
    },
    pros: [
      'Exceptional value — two full-size essences for $35',
      'Works for virtually every skin type, including sensitive',
      '96% snail mucin is one of the most studied K-beauty actives',
      'Noticeably plumping and soothing with consistent use',
      'Lightweight — layers under any moisturizer',
    ],
    cons: [
      'Gel-sticky texture is polarizing',
      'Mature skin may want a richer product alongside',
      'Retinol included is only a mini sample',
    ],
    bestFor: 'All skin types seeking deep hydration, barrier support, and a high-value K-beauty staple',
    notGreatFor: 'Those who dislike gel textures or need richer occlusive moisture for very dry skin',
    keyIngredients: ['Snail Secretion Filtrate (96%)', 'Sodium Hyaluronate', 'Arginine', 'Panthenol'],
    publishedAt: '2026-04-17',
    updatedAt: '2026-04-17',
  },
  {
    id: '9',
    slug: 'medicube-zero-pore-pad-2',
    name: 'Zero Pore Pad 2.0',
    brand: 'Medicube',
    tagline: 'K-beauty AHA/BHA pads that visibly minimize pores and refine texture — at a drugstore price.',
    description:
      'Clinically tested toner pads combining lactic acid (AHA) for surface exfoliation and salicylic acid (BHA) for deep pore-clearing. Designed for oily, combination, and normal skin types seeking smoother texture and reduced pore appearance. Use a maximum of 3 times per week; always follow with SPF. Currently on sale from $31.',
    category: ['toner', 'exfoliant'],
    skinTypes: ['oily', 'combination', 'normal'],
    skinConcerns: ['pores', 'texture', 'dullness', 'glow'],
    ingredientFocus: ['aha-bha'],
    philosophy: ['fragrance-free', 'clinical', 'cultural-heritage'],
    routineLevel: 'moderate',
    price: 18.90,
    priceRange: 'budget',
    affiliateUrl: 'https://www.amazon.com/dp/B0CW1KV8B6?tag=skincareprice-20',
    affiliatePartner: 'Amazon',
    image: '/images/products/medicube-zero-pore-pad.jpg',
    tier: 'A',
    overallScore: 8.7,
    isAgeSupport: false,
    scores: {
      results: 8.8,
      feelExperience: 8.5,
      ingredientsSafety: 8.7,
      skinCompatibility: 7.8,
      easeOfUse: 9.5,
      brandTrust: 9.0,
      priceValue: 9.4,
      aestheticPackaging: 8.2,
    },
    ageDecadeScores: {
      twenties: 9.0,
      thirties: 9.0,
      forties: 8.5,
      fifties: 7.0,
      sixtyPlus: 6.0,
    },
    pros: [
      'Exceptional value — effective AHA/BHA at a budget price',
      'Noticeably minimizes pores with consistent use',
      'Incredibly easy to use — no cotton pad needed',
      'Dermatologist-tested and fragrance-free',
      'K-beauty clinically backed formula',
    ],
    cons: [
      'Not suitable for very dry or sensitive skin',
      'Requires SPF every morning when in use',
      'Max 3x per week — overuse causes irritation',
      'Not ideal for skin in its 50s+ without gradual introduction',
    ],
    bestFor: 'Oily, combination, or normal skin with enlarged pores, uneven texture, or dullness',
    notGreatFor: 'Very dry, sensitive, or reactive skin — introduce slowly if in doubt',
    keyIngredients: ['Lactic Acid (AHA)', 'Salicylic Acid (BHA)', 'Niacinamide', 'Glycerin'],
    publishedAt: '2025-04-16',
    updatedAt: '2025-04-16',
  },
  {
    id: '11',
    slug: 'eminence-strawberry-rhubarb-masque',
    name: 'Strawberry Rhubarb Masque',
    brand: 'Eminence Organic Skin Care',
    tagline: 'Certified organic hydration and gentle brightening for every skin type.',
    description:
      'A rich, soothing mask combining organic strawberry (antioxidants, vitamin C) and rhubarb (gentle brightening acids) with hyaluronic acid for deep hydration. Calms redness, restores radiance, and supports barrier health. Use 1–2 times per week on clean skin; leave on for 5–10 minutes.',
    category: ['mask'],
    skinTypes: ['dry', 'sensitive', 'normal', 'combination', 'mature'],
    skinConcerns: ['hydration', 'redness', 'dullness', 'glow', 'barrier-repair'],
    ingredientFocus: ['hyaluronic-acid', 'antioxidants'],
    philosophy: ['clean-beauty'],
    routineLevel: 'simple',
    price: 37.79,
    priceRange: 'mid',
    affiliateUrl: 'https://www.amazon.com/dp/B06Y26TP9S?tag=skincareprice-20',
    affiliatePartner: 'Amazon',
    image: '/images/products/71sViQ1y2BL._SL1500_.jpg',
    tier: 'A',
    overallScore: 8.6,
    isAgeSupport: true,
    scores: {
      results: 8.0,
      feelExperience: 9.0,
      ingredientsSafety: 9.0,
      skinCompatibility: 9.0,
      easeOfUse: 8.5,
      brandTrust: 8.5,
      priceValue: 8.5,
      aestheticPackaging: 8.5,
    },
    ageDecadeScores: {
      twenties: 8.5,
      thirties: 8.5,
      forties: 9.0,
      fifties: 9.0,
      sixtyPlus: 8.5,
    },
    pros: [
      'Certified organic formula with no synthetic fragrance concerns',
      'Exceptionally soothing — excellent for reactive or sensitized skin',
      'Noticeable hydration boost after a single use',
      'Works beautifully across all skin types including mature skin',
    ],
    cons: [
      'Gentle brightening — not a high-potency treatment',
      'Mask format requires 5–10 minutes application time',
    ],
    bestFor: 'All skin types seeking gentle hydration, barrier support, and a weekly glow reset',
    notGreatFor: 'Those needing aggressive exfoliation or high-potency active treatment',
    keyIngredients: ['Organic Strawberry', 'Organic Rhubarb', 'Hyaluronic Acid', 'Shea Butter'],
    publishedAt: '2026-04-17',
    updatedAt: '2026-04-17',
  },
  {
    id: '12',
    slug: 'eminence-strawberry-rhubarb-dermafoliant',
    name: 'Strawberry Rhubarb Dermafoliant',
    brand: 'Eminence Organic Skin Care',
    tagline: 'A powder exfoliant that activates on contact for visible texture refinement.',
    description:
      'A dry-powder exfoliant that activates with water to deliver a dual-action exfoliation: rice starch for gentle physical buffing and rhubarb-derived acids for surface brightening. Smooths texture, minimizes pore appearance, and improves glow over time. Use 2–3 times per week; avoid if skin is very sensitive or compromised.',
    category: ['exfoliant'],
    skinTypes: ['normal', 'combination', 'oily', 'dry', 'mature'],
    skinConcerns: ['texture', 'dullness', 'pores', 'glow', 'dark-spots'],
    ingredientFocus: ['aha-bha', 'antioxidants'],
    philosophy: ['clean-beauty'],
    routineLevel: 'moderate',
    price: 37,
    priceRange: 'mid',
    affiliateUrl: 'https://www.amazon.com/dp/B003WHF148?tag=skincareprice-20',
    affiliatePartner: 'Amazon',
    image: '/images/products/strawberryrhubarbdermafoliant.jpg',
    tier: 'A',
    overallScore: 8.3,
    isAgeSupport: true,
    scores: {
      results: 8.5,
      feelExperience: 8.0,
      ingredientsSafety: 8.5,
      skinCompatibility: 7.5,
      easeOfUse: 7.5,
      brandTrust: 8.5,
      priceValue: 9.0,
      aestheticPackaging: 8.0,
    },
    ageDecadeScores: {
      twenties: 9.0,
      thirties: 9.0,
      forties: 8.5,
      fifties: 8.0,
      sixtyPlus: 7.0,
    },
    pros: [
      'Powder format lasts significantly longer than liquid exfoliants at the same price',
      'Visible texture smoothing with consistent use',
      'Certified organic — no synthetic fragrance or harsh chemicals',
      'Works well for glow maintenance between chemical peels',
    ],
    cons: [
      'Mixing required each use — less convenient than pre-formulated exfoliants',
      'Not suitable for very sensitive, reactive, or compromised skin',
      'Physical component may feel too intense for delicate skin',
    ],
    bestFor: 'Normal to oily skin seeking visible texture refinement and a brighter complexion',
    notGreatFor: 'Very sensitive, rosacea-prone, or barrier-compromised skin',
    keyIngredients: ['Organic Strawberry', 'Organic Rhubarb', 'Rice Starch', 'Willow Bark Extract'],
    publishedAt: '2026-04-17',
    updatedAt: '2026-04-17',
  },
  {
    id: '13',
    slug: 'eminence-rosehip-triple-ce-firming-oil',
    name: 'Rosehip Triple C+E Firming Oil',
    brand: 'Eminence Organic Skin Care',
    tagline: 'A certified organic face oil delivering vitamin C, vitamin E, and rosehip for visible radiance and barrier nourishment.',
    description:
      'A certified organic firming face oil combining rosehip seed oil with triple vitamin C and vitamin E for antioxidant protection, brightening, and barrier nourishment. Absorbs quickly without heaviness. Best for dry, normal, and mature skin seeking visible glow and structural support.',
    category: ['face-oil'],
    skinTypes: ['dry', 'normal', 'mature'],
    skinConcerns: ['firmness', 'glow', 'fine-lines', 'barrier-repair', 'dark-spots', 'dullness'],
    ingredientFocus: ['vitamin-c', 'antioxidants'],
    philosophy: ['clean-beauty'],
    routineLevel: 'simple',
    price: 65,
    priceRange: 'premium',
    affiliateUrl: 'https://www.amazon.com/dp/B077C4HRLD?tag=skincareprice-20',
    affiliatePartner: 'Amazon',
    image: '/images/products/rosehip.jpg',
    tier: 'A',
    overallScore: 8.5,
    isAgeSupport: true,
    scores: {
      results: 8.5,
      feelExperience: 8.5,
      ingredientsSafety: 9.0,
      skinCompatibility: 8.0,
      easeOfUse: 8.5,
      brandTrust: 8.5,
      priceValue: 8.5,
      aestheticPackaging: 8.5,
    },
    ageDecadeScores: {
      twenties: 7.0,
      thirties: 8.5,
      forties: 9.0,
      fifties: 9.0,
      sixtyPlus: 8.5,
    },
    pros: [
      'Certified organic — no synthetic fragrance or questionable actives',
      'Rosehip + vitamin C + E combination is well-supported for glow and barrier nourishment',
      'Lightweight for a face oil — absorbs without heaviness',
      'Strong value at $65 sale from $110 list',
    ],
    cons: [
      'Not suitable for oily or acne-prone skin',
      'Vitamin C in oil form is less potent than dedicated vitamin C serums',
    ],
    bestFor: 'Dry, normal, or mature skin seeking a nourishing, antioxidant-rich face oil with organic credentials',
    notGreatFor: 'Oily, combination, or acne-prone skin types',
    keyIngredients: ['Rosehip Seed Oil', 'Vitamin C (Triple Complex)', 'Vitamin E', 'Organic Jojoba Oil'],
    publishedAt: '2026-04-17',
    updatedAt: '2026-04-17',
  },
  {
    id: '14',
    slug: 'youth-to-the-people-superberry-dream-mask',
    name: 'Superberry Hydrate + Glow Dream Mask',
    brand: 'Youth To The People',
    tagline: 'An overnight antioxidant mask that wakes up dull, dehydrated skin with superberry power.',
    description:
      'A leave-on overnight treatment mask blending hyaluronic acid, vitamin C, and a superberry complex (maqui, acai, blueberry) for deep hydration, antioxidant nourishment, and morning glow. Use as a sleeping mask 2–3 nights per week or as a 10-minute rinse-off treatment.',
    category: ['mask'],
    skinTypes: ['dry', 'oily', 'combination', 'sensitive', 'normal', 'mature'],
    skinConcerns: ['hydration', 'glow', 'dullness', 'barrier-repair', 'dark-spots'],
    ingredientFocus: ['hyaluronic-acid', 'vitamin-c', 'antioxidants'],
    philosophy: ['clean-beauty', 'vegan', 'sustainable', 'cruelty-free'],
    routineLevel: 'simple',
    price: 53,
    priceRange: 'premium',
    affiliateUrl: 'https://www.amazon.com/dp/B07PH2BBKS?tag=skincareprice-20',
    affiliatePartner: 'Amazon',
    image: '/images/products/strawberryhydrationdreams.jpg',
    tier: 'A',
    overallScore: 8.7,
    isAgeSupport: true,
    scores: {
      results: 8.5,
      feelExperience: 9.0,
      ingredientsSafety: 9.0,
      skinCompatibility: 9.0,
      easeOfUse: 9.0,
      brandTrust: 8.5,
      priceValue: 7.5,
      aestheticPackaging: 9.0,
    },
    ageDecadeScores: {
      twenties: 9.0,
      thirties: 9.0,
      forties: 8.5,
      fifties: 8.0,
      sixtyPlus: 7.5,
    },
    pros: [
      'Works as both an overnight mask and a rinse-off treatment',
      'Universal skin compatibility — works across all skin types',
      'Superberry antioxidant complex is genuinely well-formulated',
      'Strong clean beauty, vegan, and sustainability credentials',
      'Beautiful texture and sensory experience',
    ],
    cons: [
      'Premium price for a mask format',
      'Mature skin may want a richer overnight treatment alongside',
    ],
    bestFor: 'All skin types seeking overnight antioxidant nourishment and a visible morning glow reset',
    notGreatFor: 'Those needing richer occlusive moisture for very dry or mature skin as a standalone overnight product',
    keyIngredients: ['Maqui Berry', 'Acai', 'Blueberry Extract', 'Hyaluronic Acid', 'Vitamin C'],
    publishedAt: '2026-04-17',
    updatedAt: '2026-04-17',
  },
  {
    id: '15',
    slug: 'golden-secrets-clear-confident-skin-kit',
    name: 'Clear Confident Skin Kit',
    brand: 'The Golden Secrets',
    tagline: 'A complete Ayurvedic-inspired kit for clearer, more radiant skin — Think Dirty Verified.',
    description:
      'A curated multi-step kit targeting blemishes, uneven tone, and skin clarity using The Golden Secrets\' signature plant-based, Ayurvedic-inspired formulations. Think Dirty Verified across the range. Best suited to skin in its 20s–40s seeking a clean, holistic approach to clearer skin without compromising the barrier.',
    category: ['serum', 'moisturizer'],
    skinTypes: ['dry', 'oily', 'combination', 'sensitive', 'normal', 'mature'],
    skinConcerns: ['pores', 'texture', 'glow', 'dark-spots', 'dullness'],
    ingredientFocus: ['antioxidants', 'plant-stem-cells'],
    philosophy: ['clean-beauty', 'luxury', 'cultural-heritage'],
    routineLevel: 'moderate',
    price: 356,
    priceRange: 'luxury',
    affiliateUrl: 'https://bit.ly/3xwBvkm',
    affiliatePartner: 'The Golden Secrets',
    image: '/images/products/golden-secrets-clear-confident-kit.jpg',
    tier: 'A',
    overallScore: 8.3,
    isAgeSupport: true,
    scores: {
      results: 8.5,
      feelExperience: 8.5,
      ingredientsSafety: 8.5,
      skinCompatibility: 8.0,
      easeOfUse: 8.0,
      brandTrust: 8.5,
      priceValue: 7.5,
      aestheticPackaging: 9.0,
    },
    ageDecadeScores: {
      twenties: 9.0,
      thirties: 9.0,
      forties: 8.5,
      fifties: 7.5,
      sixtyPlus: 7.0,
    },
    pros: [
      'Think Dirty Verified — one of the most rigorous clean beauty certifications',
      'Holistic kit approach addresses clarity from multiple angles',
      'Ayurvedic-rooted formulations with strong botanical credentials',
      'Beautiful packaging and sensory experience',
    ],
    cons: [
      'Premium price point — significant investment',
      'Kit format means less flexibility to swap individual products',
      'Best suited to 20s–40s skin; less targeted for mature skin needs',
    ],
    bestFor: 'Skin in its 20s–40s seeking a complete, clean approach to clarity and a more even, radiant complexion',
    notGreatFor: 'Those looking for clinical-strength acne treatment or a lower price entry point',
    keyIngredients: ['24k Gold', 'Turmeric', 'Rosehip Oil', 'Neem', 'Plant Stem Cells'],
    publishedAt: '2026-04-17',
    updatedAt: '2026-04-17',
  },
  {
    id: '16',
    slug: 'golden-secrets-deluxe-minis',
    name: 'Deluxe Minis',
    brand: 'The Golden Secrets',
    tagline: 'The lowest-commitment way to try The Golden Secrets — travel-ready, full-quality.',
    description:
      'A set of deluxe mini samples across The Golden Secrets\' core range, allowing you to experience the brand\'s Think Dirty Verified, Ayurvedic-inspired formulations before committing to full sizes. At $5, this is an exceptional entry point. Works for all skin types and ages. Perfect for travel or bag essentials.',
    category: ['serum', 'face-oil'],
    skinTypes: ['dry', 'oily', 'combination', 'sensitive', 'normal', 'mature'],
    skinConcerns: ['hydration', 'glow', 'barrier-repair', 'dullness', 'firmness'],
    ingredientFocus: ['antioxidants', 'plant-stem-cells'],
    philosophy: ['clean-beauty', 'luxury', 'cultural-heritage'],
    routineLevel: 'simple',
    price: 5,
    priceRange: 'budget',
    affiliateUrl: 'https://bit.ly/3xwBvkm',
    affiliatePartner: 'The Golden Secrets',
    image: '/images/products/golden-secrets-deluxe-minis.jpg',
    tier: 'A',
    overallScore: 8.5,
    isAgeSupport: true,
    scores: {
      results: 7.5,
      feelExperience: 8.5,
      ingredientsSafety: 8.5,
      skinCompatibility: 9.0,
      easeOfUse: 9.5,
      brandTrust: 8.5,
      priceValue: 10.0,
      aestheticPackaging: 8.5,
    },
    ageDecadeScores: {
      twenties: 8.5,
      thirties: 8.5,
      forties: 8.5,
      fifties: 8.5,
      sixtyPlus: 8.5,
    },
    pros: [
      'Exceptional value — $5 entry point to a luxury clean brand',
      'Think Dirty Verified formulations in travel-ready format',
      'Zero-risk way to find your Golden Secrets match before full-size investment',
      'Works for every skin type and decade',
    ],
    cons: [
      'Sample sizes do not allow full assessment of long-term results',
      'Not a standalone routine — a trial, not a commitment',
    ],
    bestFor: 'Anyone curious about The Golden Secrets wanting to try before investing in full sizes',
    keyIngredients: ['24k Gold', 'Turmeric', 'Rosehip Oil', 'Sea Buckthorn', 'Vitamin E'],
    publishedAt: '2026-04-17',
    updatedAt: '2026-04-17',
  },
  {
    id: '17',
    slug: 'golden-secrets-womb-wisdom-oil',
    name: 'Womb Wisdom Skin-Toning Oil',
    brand: 'The Golden Secrets',
    tagline: 'A deeply nourishing body oil rooted in Ayurvedic tradition — for toned, supple, radiant skin.',
    description:
      'A luxurious body oil combining Ayurvedic botanical oils and plant actives to nourish, tone, and support skin vitality from the outside in. Think Dirty Verified. Absorbs quickly without greasiness. Use daily on damp skin post-shower for best results. Especially supportive for skin in its 30s–60s+.',
    category: ['face-oil'],
    skinTypes: ['dry', 'oily', 'combination', 'sensitive', 'normal', 'mature'],
    skinConcerns: ['firmness', 'texture', 'hydration', 'barrier-repair', 'glow'],
    ingredientFocus: ['antioxidants', 'plant-stem-cells'],
    philosophy: ['clean-beauty', 'luxury', 'cultural-heritage'],
    routineLevel: 'simple',
    price: 80,
    priceRange: 'premium',
    affiliateUrl: 'https://bit.ly/3xwBvkm',
    affiliatePartner: 'The Golden Secrets',
    image: '/images/products/golden-secrets-womb-wisdom-oil.jpg',
    tier: 'A',
    overallScore: 8.7,
    isAgeSupport: true,
    scores: {
      results: 8.0,
      feelExperience: 9.5,
      ingredientsSafety: 9.0,
      skinCompatibility: 9.0,
      easeOfUse: 9.0,
      brandTrust: 8.5,
      priceValue: 8.0,
      aestheticPackaging: 9.0,
    },
    ageDecadeScores: {
      twenties: 7.5,
      thirties: 8.5,
      forties: 9.0,
      fifties: 9.0,
      sixtyPlus: 8.5,
    },
    pros: [
      'Exceptional sensory experience — a ritual, not just a step',
      'Think Dirty Verified with a deeply clean botanical ingredient profile',
      'Nourishes and supports skin suppleness with consistent use',
      'Fast-absorbing body oil with no greasy residue',
    ],
    cons: [
      'Body toning claims are softer than clinical actives can deliver',
      'Higher price point for a body oil',
    ],
    bestFor: 'All skin types seeking a clean, nourishing body oil that supports skin vitality and suppleness as a daily ritual',
    keyIngredients: ['Ayurvedic Botanical Oils', 'Turmeric', 'Sea Buckthorn', 'Vitamin E', 'Rosehip Oil'],
    publishedAt: '2026-04-17',
    updatedAt: '2026-04-17',
  },
  {
    id: '18',
    slug: 'golden-secrets-body-sculpting-kit',
    name: 'Body Sculpting Kit',
    brand: 'The Golden Secrets',
    tagline: 'A complete clean body nourishment system for firmer, more supple skin.',
    description:
      'A curated multi-product kit combining The Golden Secrets\' body-focused formulations for a complete skin nourishment and toning routine. Think Dirty Verified. Designed for skin in its 30s–60s+ seeking a meaningful upgrade to body skincare using clean, Ayurvedic-rooted botanicals.',
    category: ['face-oil', 'moisturizer'],
    skinTypes: ['dry', 'oily', 'combination', 'sensitive', 'normal', 'mature'],
    skinConcerns: ['firmness', 'texture', 'hydration', 'glow', 'barrier-repair'],
    ingredientFocus: ['antioxidants', 'plant-stem-cells'],
    philosophy: ['clean-beauty', 'luxury', 'cultural-heritage'],
    routineLevel: 'moderate',
    price: 240,
    priceRange: 'luxury',
    affiliateUrl: 'https://bit.ly/3xwBvkm',
    affiliatePartner: 'The Golden Secrets',
    image: '/images/products/golden-secrets-body-sculpting-kit.jpg',
    tier: 'A',
    overallScore: 8.6,
    isAgeSupport: true,
    scores: {
      results: 8.5,
      feelExperience: 9.0,
      ingredientsSafety: 9.0,
      skinCompatibility: 8.5,
      easeOfUse: 8.0,
      brandTrust: 8.5,
      priceValue: 8.0,
      aestheticPackaging: 9.0,
    },
    ageDecadeScores: {
      twenties: 7.0,
      thirties: 8.5,
      forties: 9.0,
      fifties: 9.0,
      sixtyPlus: 8.5,
    },
    pros: [
      'Think Dirty Verified — clean credentials across the full kit',
      'Strong bundle savings from $268 list price',
      'Ayurvedic botanical formulations with a genuine cultural heritage',
      'Luxurious multi-step body ritual with excellent sensory payoff',
    ],
    cons: [
      'Significant investment — best approached as a considered upgrade',
      'Kit format limits substituting individual products',
    ],
    bestFor: 'Skin in its 30s–60s+ seeking a complete, clean body nourishment routine with real botanical efficacy',
    notGreatFor: 'Those wanting a minimal, single-product body routine or a lower price entry point',
    keyIngredients: ['Ayurvedic Botanical Oils', '24k Gold', 'Turmeric', 'Rosehip Oil', 'Sea Buckthorn'],
    publishedAt: '2026-04-17',
    updatedAt: '2026-04-17',
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByTier(tier: string): Product[] {
  return PRODUCTS.filter((p) => p.tier === tier);
}

export function getAgeSupportProducts(): Product[] {
  return PRODUCTS.filter((p) => p.isAgeSupport);
}
