import type { Product } from './types';
import { calcOverallScore } from './scoring';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    slug: 'the-golden-secrets-face-serum',
    name: 'The Golden Secrets Face Serum',
    brand: 'The Golden Secrets',
    tagline: 'Luxury meets function — skin support rooted in Ayurvedic wisdom.',
    description:
      'A richly formulated serum blending 24k gold, plant actives, and botanical oils. Designed to nourish and restore radiance while supporting the skin barrier.',
    category: ['serum'],
    skinTypes: ['dry', 'normal', 'mature'],
    skinConcerns: ['hydration', 'glow', 'firmness', 'dullness'],
    ingredientFocus: ['antioxidants', 'plant-stem-cells'],
    philosophy: ['clean-beauty', 'luxury', 'cultural-heritage'],
    routineLevel: 'moderate',
    price: 89,
    priceRange: 'premium',
    affiliateUrl: 'https://bit.ly/3xwBvkm',
    affiliatePartner: 'The Golden Secrets',
    image: '/images/products/golden-secrets-serum.jpg',
    tier: 'A',
    overallScore: 8.4,
    isAgeSupport: true,
    scores: {
      results: 8.5,
      feelExperience: 9.0,
      ingredientsSafety: 8.0,
      skinCompatibility: 8.5,
      easeOfUse: 9.0,
      brandTrust: 8.0,
      priceValue: 7.5,
      aestheticPackaging: 9.5,
    },
    ageDecadeScores: {
      twenties: 7.5,
      thirties: 8.5,
      forties: 9.0,
      fifties: 8.5,
      sixtyPlus: 8.0,
    },
    pros: [
      'Deeply nourishing without heaviness',
      'Visible glow within 1–2 weeks',
      'Beautiful sensory experience',
      'Clean ingredient profile',
    ],
    cons: ['Premium price point', 'Not ideal for oily or acne-prone skin'],
    bestFor: 'Dry to normal skin seeking a luxurious daily radiance serum',
    notGreatFor: 'Oily or acne-prone skin types',
    keyIngredients: ['24k Gold', 'Rosehip Oil', 'Sea Buckthorn', 'Turmeric', 'Vitamin E'],
    publishedAt: '2024-09-01',
    updatedAt: '2025-01-15',
  },
  {
    id: '2',
    slug: 'osea-ocean-cleanser',
    name: 'Ocean Cleanser',
    brand: 'OSEA',
    tagline: 'Seaweed-powered cleansing that respects your barrier.',
    description:
      "A gentle, sulfate-free gel cleanser formulated with OSEA's signature seaweed blend. Removes impurities without stripping skin of its natural moisture.",
    category: ['cleanser'],
    skinTypes: ['normal', 'combination', 'sensitive', 'dry'],
    skinConcerns: ['hydration', 'barrier-repair', 'redness'],
    ingredientFocus: ['sea-actives', 'antioxidants'],
    philosophy: ['clean-beauty', 'vegan', 'cruelty-free', 'reef-safe', 'sustainable'],
    routineLevel: 'simple',
    price: 48,
    priceRange: 'mid',
    affiliateUrl:
      'https://oseamalibu.com/?rfsn=7790532.88631ca&utm_source=refersion&utm_medium=affiliate&utm_campaign=7790532.88631ca',
    affiliatePartner: 'OSEA',
    image: '/images/products/osea-ocean-cleanser.jpg',
    tier: 'A',
    overallScore: 8.6,
    isAgeSupport: true,
    scores: {
      results: 8.5,
      feelExperience: 9.0,
      ingredientsSafety: 9.5,
      skinCompatibility: 9.0,
      easeOfUse: 9.5,
      brandTrust: 9.0,
      priceValue: 8.0,
      aestheticPackaging: 8.0,
    },
    ageDecadeScores: {
      twenties: 9.0,
      thirties: 9.0,
      forties: 8.5,
      fifties: 8.5,
      sixtyPlus: 8.0,
    },
    pros: [
      'Works for nearly all skin types',
      'Reef-safe and sustainably sourced',
      'Leaves skin soft, not tight',
      'Strong clean beauty ethos',
    ],
    cons: ['Some find the seaweed scent polarizing', 'No heavy-duty makeup removal'],
    bestFor: 'Everyday cleansing for sensitive and normal skin types seeking clean formulas',
    keyIngredients: ['Atlantic Kelp', 'Bladderwrack Seaweed', 'Aloe Vera', 'Glycerin'],
    publishedAt: '2024-08-15',
    updatedAt: '2025-02-01',
  },
  {
    id: '3',
    slug: 'osea-undaria-algae-body-serum',
    name: 'Undaria Algae Body Serum',
    brand: 'OSEA',
    tagline: 'Award-winning body serum for visibly smoother, nourished skin.',
    description:
      "OSEA's hero product — a lightweight, fast-absorbing body serum packed with nutrient-rich Undaria algae. Clinically shown to improve skin texture and hydration.",
    category: ['serum'],
    skinTypes: ['dry', 'normal', 'combination', 'mature'],
    skinConcerns: ['texture', 'hydration', 'firmness', 'glow'],
    ingredientFocus: ['sea-actives', 'antioxidants', 'hyaluronic-acid'],
    philosophy: ['clean-beauty', 'vegan', 'cruelty-free', 'reef-safe', 'sustainable'],
    routineLevel: 'simple',
    price: 68,
    priceRange: 'premium',
    affiliateUrl:
      'https://oseamalibu.com/?rfsn=7790532.88631ca&utm_source=refersion&utm_medium=affiliate&utm_campaign=7790532.88631ca',
    affiliatePartner: 'OSEA',
    image: '/images/products/osea-undaria-serum.jpg',
    tier: 'S',
    overallScore: 9.1,
    isAgeSupport: true,
    scores: {
      results: 9.5,
      feelExperience: 9.5,
      ingredientsSafety: 9.5,
      skinCompatibility: 9.0,
      easeOfUse: 9.5,
      brandTrust: 9.0,
      priceValue: 8.5,
      aestheticPackaging: 8.5,
    },
    ageDecadeScores: {
      twenties: 8.5,
      thirties: 9.0,
      forties: 9.5,
      fifties: 9.5,
      sixtyPlus: 9.0,
    },
    pros: [
      'Clinically proven texture improvement',
      'Fast-absorbing, never greasy',
      'One of the cleanest body serums on the market',
      'Award-winning formula',
    ],
    cons: ['Price point higher than most body lotions', 'Scented — may not suit fragrance-sensitive skin'],
    bestFor: 'Anyone wanting clinically-backed, clean body skin support in one step',
    keyIngredients: ['Undaria Pinnatifida Algae', 'Hyaluronic Acid', 'Vitamin C', 'Niacinamide'],
    publishedAt: '2024-07-01',
    updatedAt: '2025-03-01',
  },
  {
    id: '4',
    slug: 'true-botanicals-vitamin-c-booster',
    name: 'Vitamin C Booster',
    brand: 'True Botanicals',
    tagline: 'Stabilized, potent Vitamin C that actually delivers.',
    description:
      'A concentrated Vitamin C powder that activates on contact with your serum or moisturizer. One of the most stable and effective Vitamin C formulations in clean beauty.',
    category: ['serum'],
    skinTypes: ['normal', 'combination', 'dry', 'mature'],
    skinConcerns: ['dark-spots', 'dullness', 'glow', 'firmness', 'fine-lines'],
    ingredientFocus: ['vitamin-c', 'antioxidants'],
    philosophy: ['clean-beauty', 'cruelty-free', 'sustainable', 'clinical'],
    routineLevel: 'moderate',
    price: 110,
    priceRange: 'luxury',
    affiliateUrl: 'https://true-botanicals.sjv.io/E09GAX',
    affiliatePartner: 'True Botanicals',
    image: '/images/products/true-botanicals-vitamin-c.jpg',
    tier: 'S',
    overallScore: 9.2,
    isAgeSupport: true,
    scores: {
      results: 9.5,
      feelExperience: 8.0,
      ingredientsSafety: 9.5,
      skinCompatibility: 9.0,
      easeOfUse: 7.5,
      brandTrust: 9.5,
      priceValue: 8.0,
      aestheticPackaging: 9.0,
    },
    ageDecadeScores: {
      twenties: 8.0,
      thirties: 9.0,
      forties: 9.5,
      fifties: 9.5,
      sixtyPlus: 9.0,
    },
    pros: [
      'Exceptional stability vs. liquid Vitamin C',
      'Highly bioavailable form (THD Ascorbate)',
      'Certified MADE SAFE',
      'Visible brightening within 4 weeks',
    ],
    cons: [
      'Learning curve with the powder format',
      'Luxury price point',
      'Needs a "carrier" product',
    ],
    bestFor: 'Committed routines seeking next-level brightening and skin tone support',
    notGreatFor: 'Beginners or those wanting a simple, one-step product',
    keyIngredients: ['THD Ascorbate (Vitamin C)', 'Ferulic Acid', 'Vitamin E'],
    publishedAt: '2024-06-15',
    updatedAt: '2025-01-20',
  },
  {
    id: '5',
    slug: 'juara-turmeric-antioxidant-radiance-mask',
    name: 'Turmeric Antioxidant Radiance Mask',
    brand: 'Juara Skincare',
    tagline: 'Jamu-inspired radiance rooted in Indonesian heritage.',
    description:
      'A rich, warming mask drawing on centuries-old Jamu traditions. Turmeric, candlenut, and clove oil deliver deep antioxidant support while evening skin tone and promoting warmth and glow.',
    category: ['mask'],
    skinTypes: ['normal', 'dry', 'combination', 'mature'],
    skinConcerns: ['glow', 'dullness', 'dark-spots', 'hydration'],
    ingredientFocus: ['antioxidants', 'plant-stem-cells'],
    philosophy: ['clean-beauty', 'cruelty-free', 'vegan', 'cultural-heritage'],
    routineLevel: 'moderate',
    price: 38,
    priceRange: 'mid',
    affiliateUrl: 'https://juara-skincare.sjv.io/enqBXZ',
    affiliatePartner: 'Juara Skincare',
    image: '/images/products/juara-turmeric-mask.jpg',
    tier: 'A',
    overallScore: 8.3,
    isAgeSupport: true,
    scores: {
      results: 8.5,
      feelExperience: 9.0,
      ingredientsSafety: 8.5,
      skinCompatibility: 8.0,
      easeOfUse: 8.5,
      brandTrust: 8.5,
      priceValue: 9.0,
      aestheticPackaging: 8.0,
    },
    ageDecadeScores: {
      twenties: 8.0,
      thirties: 8.5,
      forties: 8.5,
      fifties: 8.0,
      sixtyPlus: 7.5,
    },
    pros: [
      'Immediate glow boost',
      'Beautiful ritual sensory experience',
      'Affordable luxury',
      'Rooted in real cultural tradition',
    ],
    cons: ['Turmeric can temporarily stain skin/towels if left too long', 'Once-weekly use only'],
    bestFor: 'Anyone wanting an antioxidant ritual that feels indulgent without a luxury price tag',
    keyIngredients: ['Turmeric Root', 'Candlenut Oil', 'Clove', 'Tamanu Oil', 'Coconut Milk'],
    publishedAt: '2024-10-01',
    updatedAt: '2025-02-15',
  },
  {
    id: '6',
    slug: 'shani-darden-texture-reform',
    name: 'Texture Reform Resurfacing Serum',
    brand: 'Shani Darden',
    tagline: 'Celebrity esthetician-formulated retinol that earns its reputation.',
    description:
      "Shani Darden's breakthrough formula combining lactic acid and encapsulated retinol for visible texture refinement. One of the most effective non-irritating exfoliant serums available.",
    category: ['serum', 'exfoliant'],
    skinTypes: ['normal', 'combination', 'oily', 'mature'],
    skinConcerns: ['texture', 'fine-lines', 'pores', 'dark-spots', 'anti-aging'],
    ingredientFocus: ['retinol', 'aha-bha'],
    philosophy: ['clinical', 'cruelty-free'],
    routineLevel: 'advanced',
    price: 88,
    priceRange: 'premium',
    affiliateUrl: 'https://shanidarden.sjv.io/5kAmzn',
    affiliatePartner: 'Shani Darden',
    image: '/images/products/shani-darden-texture-reform.jpg',
    tier: 'S',
    overallScore: 9.0,
    isAgeSupport: false,
    scores: {
      results: 9.5,
      feelExperience: 8.5,
      ingredientsSafety: 8.5,
      skinCompatibility: 8.5,
      easeOfUse: 8.0,
      brandTrust: 9.5,
      priceValue: 8.5,
      aestheticPackaging: 9.0,
    },
    ageDecadeScores: {
      twenties: 8.5,
      thirties: 9.5,
      forties: 9.0,
      fifties: 8.5,
      sixtyPlus: 7.5,
    },
    pros: [
      'Clinically effective texture resurfacing',
      'Retinol well-tolerated by most skin types',
      'Visible results in 4–6 weeks',
      'Trusted by professional estheticians',
    ],
    cons: ['Requires SPF during the day', 'Not for sensitive/reactive skin', 'No at night only use'],
    bestFor: 'Those wanting real skin texture improvement with clinical efficacy',
    notGreatFor: 'Sensitive, rosacea-prone, or retinol-naive skin without proper introduction',
    keyIngredients: ['Encapsulated Retinol', 'Lactic Acid', 'Niacinamide', 'Glycerin'],
    publishedAt: '2024-05-01',
    updatedAt: '2025-01-10',
  },
  {
    id: '7',
    slug: 'osea-hyaluronic-sea-serum',
    name: 'Hyaluronic Sea Serum',
    brand: 'OSEA',
    tagline: 'Plumping, weightless hydration from the deep sea.',
    description:
      "A featherlight serum delivering three weights of hyaluronic acid alongside OSEA's signature seaweed complex for multi-depth hydration. Works for every skin type.",
    category: ['serum'],
    skinTypes: ['dry', 'oily', 'combination', 'sensitive', 'normal', 'mature'],
    skinConcerns: ['hydration', 'barrier-repair', 'fine-lines'],
    ingredientFocus: ['hyaluronic-acid', 'sea-actives'],
    philosophy: ['clean-beauty', 'vegan', 'cruelty-free', 'reef-safe'],
    routineLevel: 'simple',
    price: 72,
    priceRange: 'premium',
    affiliateUrl:
      'https://oseamalibu.com/?rfsn=7790532.88631ca&utm_source=refersion&utm_medium=affiliate&utm_campaign=7790532.88631ca',
    affiliatePartner: 'OSEA',
    image: '/images/products/osea-ha-serum.jpg',
    tier: 'A',
    overallScore: 8.8,
    isAgeSupport: true,
    scores: {
      results: 9.0,
      feelExperience: 9.5,
      ingredientsSafety: 9.5,
      skinCompatibility: 9.5,
      easeOfUse: 9.5,
      brandTrust: 9.0,
      priceValue: 7.5,
      aestheticPackaging: 8.5,
    },
    ageDecadeScores: {
      twenties: 9.0,
      thirties: 9.0,
      forties: 9.0,
      fifties: 8.5,
      sixtyPlus: 8.5,
    },
    pros: [
      'Works beautifully across all skin types',
      'Multi-weight HA for surface and deep hydration',
      'Lightweight — layers under everything',
      'Exceptional clean beauty credentials',
    ],
    cons: ['Premium price for a HA serum', 'Must be applied to damp skin for best results'],
    bestFor: 'Anyone seeking a reliable, clean hydration serum as a routine staple',
    keyIngredients: ['3-Weight Hyaluronic Acid', 'Atlantic Kelp', 'Spirulina', 'Sea Buckthorn'],
    publishedAt: '2024-08-01',
    updatedAt: '2025-02-28',
  },
  {
    id: '8',
    slug: 'true-botanicals-pure-radiance-oil',
    name: 'Pure Radiance Oil',
    brand: 'True Botanicals',
    tagline: 'A single-ingredient nourishing face oil that works.',
    description:
      "True Botanicals' cult-status face oil made with Camellia seed oil. Clinically tested, fragrance-free, and one of the most universally compatible face oils on the market.",
    category: ['face-oil'],
    skinTypes: ['dry', 'normal', 'mature', 'sensitive'],
    skinConcerns: ['hydration', 'barrier-repair', 'glow', 'firmness'],
    ingredientFocus: ['antioxidants'],
    philosophy: ['clean-beauty', 'cruelty-free', 'fragrance-free', 'clinical', 'minimalist'],
    routineLevel: 'simple',
    price: 110,
    priceRange: 'luxury',
    affiliateUrl: 'https://true-botanicals.sjv.io/E09GAX',
    affiliatePartner: 'True Botanicals',
    image: '/images/products/true-botanicals-radiance-oil.jpg',
    tier: 'A',
    overallScore: 8.7,
    isAgeSupport: true,
    scores: {
      results: 9.0,
      feelExperience: 9.0,
      ingredientsSafety: 9.5,
      skinCompatibility: 9.0,
      easeOfUse: 9.0,
      brandTrust: 9.5,
      priceValue: 7.0,
      aestheticPackaging: 8.5,
    },
    ageDecadeScores: {
      twenties: 7.5,
      thirties: 8.5,
      forties: 9.0,
      fifties: 9.0,
      sixtyPlus: 9.0,
    },
    pros: [
      'Fragrance-free and MADE SAFE certified',
      'Exceptional for dry and mature skin types',
      'Clinically tested efficacy',
      'One of the cleanest face oils available',
    ],
    cons: ['Very high price for a single-ingredient oil', 'Not ideal for oily/acne-prone skin'],
    bestFor: 'Dry, mature, or sensitive skin seeking a clean, fragrance-free nourishing face oil',
    keyIngredients: ['Camellia japonica Seed Oil', 'Squalane'],
    publishedAt: '2024-04-15',
    updatedAt: '2025-01-05',
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByTier(tier: string): Product[] {
  return PRODUCTS.filter((p) => p.tier === tier);
}

export function getAgeSupportProducts(): Product[] {
  return PRODUCTS.filter((p) => p.isAgeSupport);
}
